/**
 * G-code parser — Sprint 1, Phase 2.
 * Pure, synchronous, never throws.
 * Only inspects the first 200 lines for performance.
 */

import type { GcodeData, SlicerType } from '@/types/gcode'

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/** Extract the first numeric capture group from a string using a regex. */
function extractNumber(line: string, re: RegExp): number | null {
  const m = re.exec(line)
  if (!m) return null
  const n = parseFloat(m[1])
  return isNaN(n) ? null : n
}

/** Extract the first string capture group, trimmed. */
function extractString(line: string, re: RegExp): string | null {
  const m = re.exec(line)
  if (!m) return null
  const s = m[1].trim()
  return s.length > 0 ? s : null
}

/**
 * Parse a PrusaSlicer/OrcaSlicer time string like "1h 30m 25s" into minutes.
 * Accepts any combination of hours, minutes, seconds (all optional).
 */
function parsePrusaTime(raw: string): number | null {
  const hoursMatch = /(\d+)\s*h/.exec(raw)
  const minutesMatch = /(\d+)\s*m/.exec(raw)
  const secondsMatch = /(\d+)\s*s/.exec(raw)
  const h = hoursMatch ? parseInt(hoursMatch[1], 10) : 0
  const m = minutesMatch ? parseInt(minutesMatch[1], 10) : 0
  const s = secondsMatch ? parseInt(secondsMatch[1], 10) : 0
  const total = h * 60 + m + s / 60
  return total > 0 ? total : null
}

/**
 * Calculate filament weight in grams from linear length.
 * Formula: mm × π × (diameter/2)² × density / 1000
 */
function gramsFromMm(mm: number, diameter: number, density: number): number {
  const radius = diameter / 2
  return mm * Math.PI * radius * radius * density / 1000
}

// ---------------------------------------------------------------------------
// Slicer detection (order matters — Orca BEFORE Prusa)
// ---------------------------------------------------------------------------

function detectSlicer(lines: string[]): { slicerType: SlicerType; slicerName: string } | null {
  const header = lines.join('\n').toLowerCase()

  // OrcaSlicer MUST be checked before PrusaSlicer (fork shares base comments)
  const orcaMatch = /generated by orcaslicer ([\d.]+)/i.exec(lines.join('\n'))
  if (orcaMatch) {
    return { slicerType: 'orcaslicer', slicerName: `OrcaSlicer ${orcaMatch[1]}` }
  }

  const prusaMatch = /generated by prusaslicer ([\d.]+)/i.exec(lines.join('\n'))
  if (prusaMatch) {
    return { slicerType: 'prusaslicer', slicerName: `PrusaSlicer ${prusaMatch[1]}` }
  }

  // BambuStudio
  const bambuMatch = /generated by bambustudio ([\w.]+)/i.exec(lines.join('\n'))
  if (bambuMatch || header.includes('bambu studio') || lines.some(l => /;\s*machine_name\s*=/.test(l) && /bambu/i.test(l))) {
    const vMatch = /generated by bambustudio ([\w.]+)/i.exec(lines.join('\n'))
    return { slicerType: 'bambustudio', slicerName: vMatch ? `BambuStudio ${vMatch[1]}` : 'BambuStudio' }
  }

  // Cura
  const curaMatch = /Generated with Cura_SteamEngine ([\d.]+)/.exec(lines.join('\n'))
    ?? /Generated with Cura ([\d.]+)/.exec(lines.join('\n'))
  if (curaMatch) {
    return { slicerType: 'cura', slicerName: `Cura ${curaMatch[1]}` }
  }

  // Simplify3D
  const s3dMatch = /Simplify3D[^\n\r]*Version ([\d.]+)/i.exec(lines.join('\n'))
    ?? /Sliced by Simplify3D ([\d.]+)/i.exec(lines.join('\n'))
  if (s3dMatch) {
    return { slicerType: 'simplify3d', slicerName: `Simplify3D ${s3dMatch[1]}` }
  }
  // Fallback Simplify3D detection via distinctive comment format
  if (lines.some(l => /;\s+printMaterial,/.test(l)) || lines.some(l => /;\s+machineType,/.test(l))) {
    return { slicerType: 'simplify3d', slicerName: 'Simplify3D' }
  }

  return null
}

// ---------------------------------------------------------------------------
// Per-slicer extractors
// ---------------------------------------------------------------------------

function extractCura(lines: string[], diameter: number, density: number): Partial<GcodeData> {
  let estimatedTimeMinutes: number | null = null
  let filamentUsedMm: number | null = null
  let filamentUsedGrams: number | null = null
  let layerCount: number | null = null
  let nozzleTemp: number | null = null
  let bedTemp: number | null = null
  let printerIdentifier: string | null = null
  let filamentType: string | null = null

  for (const line of lines) {
    if (estimatedTimeMinutes === null) {
      const t = extractNumber(line, /^;TIME:(\d+(?:\.\d+)?)/)
      if (t !== null) estimatedTimeMinutes = t / 60
    }
    if (filamentUsedMm === null) {
      const f = extractNumber(line, /^;Filament used:\s*([\d.]+)\s*mm/)
      if (f !== null) {
        filamentUsedMm = f
        filamentUsedGrams = gramsFromMm(f, diameter, density)
      }
    }
    if (layerCount === null) {
      const lc = extractNumber(line, /^;LAYER_COUNT:(\d+)/)
      if (lc !== null) layerCount = lc
    }
    if (printerIdentifier === null) {
      const pi = extractString(line, /^;(?:MACHINE_NAME|TARGET_MACHINE\.NAME):\s*(.+)/)
      if (pi) printerIdentifier = pi
    }
    if (filamentType === null) {
      const ft = extractString(line, /^;MATERIAL:\s*(.+)/)
      if (ft) filamentType = ft
    }
    // Temperature — only capture the first occurrence
    if (nozzleTemp === null) {
      const nt = extractNumber(line, /^M1(?:04|09)\s+S(\d+)/)
      if (nt !== null) nozzleTemp = nt
    }
    if (bedTemp === null) {
      const bt = extractNumber(line, /^M1(?:40|90)\s+S(\d+)/)
      if (bt !== null) bedTemp = bt
    }
  }

  return { estimatedTimeMinutes, filamentUsedMm, filamentUsedGrams, layerCount, nozzleTemp, bedTemp, printerIdentifier, filamentType, filamentBrand: null }
}

function extractPrusa(lines: string[], diameter: number, density: number): Partial<GcodeData> {
  let estimatedTimeMinutes: number | null = null
  let filamentUsedMm: number | null = null
  let filamentUsedGrams: number | null = null
  let layerCount: number | null = null
  let nozzleTemp: number | null = null
  let bedTemp: number | null = null
  let printerIdentifier: string | null = null
  let filamentType: string | null = null
  let filamentBrand: string | null = null

  // Permissive regexes covering both PrusaSlicer (`; estimated printing time (normal mode) = …`)
  // and OrcaSlicer 2.x (`; total estimated time: 2h 13m 24s`, `; total filament used [mm] = …`).
  const TIME_RE = /^;\s*(?:total\s+estimated\s+time|estimated\s+(?:printing\s+)?time(?:\s*\([^)]*\))?)\s*[=:]\s*(.+)/i
  const FILAMENT_MM_RE = /^;\s*(?:total\s+)?filament(?:\s+used|\s+length)\s*\[mm\]\s*[=:]\s*([\d.]+)/i
  const FILAMENT_G_RE = /^;\s*(?:total\s+)?filament\s+used\s*\[g\]\s*[=:]\s*([\d.]+)/i
  const LAYERS_RE = /^;\s*(?:total\s+)?layers?\s+count\s*[=:]\s*(\d+)/i

  for (const line of lines) {
    if (estimatedTimeMinutes === null) {
      const timeMatch = TIME_RE.exec(line)
      if (timeMatch) estimatedTimeMinutes = parsePrusaTime(timeMatch[1])
    }
    // Prefer the direct grams value if present — it avoids the diameter/density conversion error.
    if (filamentUsedGrams === null) {
      const g = extractNumber(line, FILAMENT_G_RE)
      if (g !== null) filamentUsedGrams = g
    }
    if (filamentUsedMm === null) {
      const f = extractNumber(line, FILAMENT_MM_RE)
      if (f !== null) {
        filamentUsedMm = f
        if (filamentUsedGrams === null) {
          filamentUsedGrams = gramsFromMm(f, diameter, density)
        }
      }
    }
    if (layerCount === null) {
      const lc = extractNumber(line, LAYERS_RE)
      if (lc !== null) layerCount = lc
    }
    if (printerIdentifier === null) {
      // prefer printer_model, fall back to printer_settings_id
      const pm = extractString(line, /^;\s*printer_model\s*=\s*(.+)/)
      if (pm) printerIdentifier = pm
    }
    if (filamentType === null) {
      const ft = extractString(line, /^;\s*filament_type\s*=\s*(.+)/)
      if (ft) filamentType = ft
    }
    if (filamentBrand === null) {
      const fb = extractString(line, /^;\s*filament_vendor\s*=\s*(.+)/)
      if (fb) filamentBrand = fb
    }
    if (nozzleTemp === null) {
      const nt = extractNumber(line, /^M1(?:04|09)\s+S(\d+)/)
      if (nt !== null) nozzleTemp = nt
    }
    if (bedTemp === null) {
      const bt = extractNumber(line, /^M1(?:40|90)\s+S(\d+)/)
      if (bt !== null) bedTemp = bt
    }

    // Early termination once every field is filled — keeps parsing fast on
    // 50k-line files where the metadata sits in the footer.
    if (
      estimatedTimeMinutes !== null &&
      filamentUsedMm !== null &&
      filamentUsedGrams !== null &&
      layerCount !== null &&
      nozzleTemp !== null &&
      bedTemp !== null &&
      printerIdentifier !== null &&
      filamentType !== null &&
      filamentBrand !== null
    ) {
      break
    }
  }

  return { estimatedTimeMinutes, filamentUsedMm, filamentUsedGrams, layerCount, nozzleTemp, bedTemp, printerIdentifier, filamentType, filamentBrand }
}

function extractOrca(lines: string[], diameter: number, density: number): Partial<GcodeData> {
  // OrcaSlicer inherits PrusaSlicer format — reuse extractor
  return extractPrusa(lines, diameter, density)
}

function extractBambu(lines: string[], diameter: number, density: number): Partial<GcodeData> {
  let estimatedTimeMinutes: number | null = null
  let filamentUsedMm: number | null = null
  let filamentUsedGrams: number | null = null
  let layerCount: number | null = null
  let nozzleTemp: number | null = null
  let bedTemp: number | null = null
  let printerIdentifier: string | null = null
  let filamentType: string | null = null
  let filamentBrand: string | null = null

  // BambuStudio formats observed across versions:
  //   `; total estimated time (s) = 5580`     (older numeric seconds)
  //   `; total estimated time: 1h 33m`        (newer HMS, with colon)
  //   `; total estimated time = 1h 33m`       (newer HMS, with equals)
  // Filament:
  //   `; total filament used [mm] = …`
  //   `; total filament used [g]  = …`
  //   `; filament used [mm] = …` (some single-material exports)
  const TIME_SECONDS_RE = /^;\s*total\s+estimated\s+time\s*\(s\)\s*[=:]\s*([\d.]+)/i
  const TIME_HMS_RE = /^;\s*total\s+estimated\s+time\s*[=:]\s*(.+)/i
  const FILAMENT_MM_RE = /^;\s*(?:total\s+)?filament\s+used\s*\[mm\]\s*[=:]\s*([\d.]+)/i
  const FILAMENT_G_RE = /^;\s*(?:total\s+)?filament\s+used\s*\[g\]\s*[=:]\s*([\d.]+)/i

  for (const line of lines) {
    if (estimatedTimeMinutes === null) {
      const t = extractNumber(line, TIME_SECONDS_RE)
      if (t !== null) estimatedTimeMinutes = t / 60
    }
    if (estimatedTimeMinutes === null) {
      const hmsMatch = TIME_HMS_RE.exec(line)
      if (hmsMatch) {
        const parsed = parsePrusaTime(hmsMatch[1])
        if (parsed !== null) estimatedTimeMinutes = parsed
      }
    }
    // Prefer grams directly when available — skips the diameter/density conversion.
    if (filamentUsedGrams === null) {
      const g = extractNumber(line, FILAMENT_G_RE)
      if (g !== null) filamentUsedGrams = g
    }
    if (filamentUsedMm === null) {
      const f = extractNumber(line, FILAMENT_MM_RE)
      if (f !== null) {
        filamentUsedMm = f
        if (filamentUsedGrams === null) {
          filamentUsedGrams = gramsFromMm(f, diameter, density)
        }
      }
    }
    if (printerIdentifier === null) {
      const pi = extractString(line, /^;\s*machine_name\s*=\s*(.+)/)
      if (pi) printerIdentifier = pi
    }
    if (filamentType === null) {
      const ft = extractString(line, /^;\s*filament_type\s*=\s*(.+)/)
      if (ft) filamentType = ft
    }
    if (filamentBrand === null) {
      const fb = extractString(line, /^;\s*filament_vendor\s*=\s*(.+)/)
      if (fb) filamentBrand = fb
    }
    if (nozzleTemp === null) {
      const nt = extractNumber(line, /^M1(?:04|09)\s+S(\d+)/)
      if (nt !== null) nozzleTemp = nt
    }
    if (bedTemp === null) {
      const bt = extractNumber(line, /^M1(?:40|90)\s+S(\d+)/)
      if (bt !== null) bedTemp = bt
    }

    if (
      estimatedTimeMinutes !== null &&
      filamentUsedGrams !== null &&
      nozzleTemp !== null &&
      bedTemp !== null &&
      printerIdentifier !== null &&
      filamentType !== null &&
      filamentBrand !== null
    ) {
      break
    }
  }

  return { estimatedTimeMinutes, filamentUsedMm, filamentUsedGrams, layerCount, nozzleTemp, bedTemp, printerIdentifier, filamentType, filamentBrand }
}

function extractSimplify3D(lines: string[], diameter: number, density: number): Partial<GcodeData> {
  let estimatedTimeMinutes: number | null = null
  let filamentUsedMm: number | null = null
  let filamentUsedGrams: number | null = null
  let layerCount: number | null = null
  let nozzleTemp: number | null = null
  let bedTemp: number | null = null
  let printerIdentifier: string | null = null
  let filamentType: string | null = null

  for (const line of lines) {
    if (estimatedTimeMinutes === null) {
      // "; Build time: X hours Y minutes" or "N hours M minutes"
      const btMatch = /^;\s+Build time:\s*(.+)/i.exec(line)
      if (btMatch) estimatedTimeMinutes = parsePrusaTime(btMatch[1])
      // Some versions: "2 hours 15 minutes" without "Build time:" label but in file header
      if (estimatedTimeMinutes === null) {
        const timeRaw = /^;.*?(\d+)\s*hours?\s*(\d+)\s*minutes?/i.exec(line)
        if (timeRaw) estimatedTimeMinutes = parseInt(timeRaw[1], 10) * 60 + parseInt(timeRaw[2], 10)
      }
    }
    if (filamentUsedMm === null) {
      const f = extractNumber(line, /^;\s+Filament used:\s*([\d.]+)\s*mm/)
      if (f !== null) {
        filamentUsedMm = f
        filamentUsedGrams = gramsFromMm(f, diameter, density)
      }
    }
    if (printerIdentifier === null) {
      const pi = extractString(line, /^;\s+machineType,(.+)/)
      if (pi) printerIdentifier = pi
    }
    if (filamentType === null) {
      const ft = extractString(line, /^;\s+printMaterial,(.+)/)
      if (ft) filamentType = ft
    }
    if (nozzleTemp === null) {
      const nt = extractNumber(line, /^M1(?:04|09)\s+S(\d+)/)
      if (nt !== null) nozzleTemp = nt
    }
    if (bedTemp === null) {
      const bt = extractNumber(line, /^M1(?:40|90)\s+S(\d+)/)
      if (bt !== null) bedTemp = bt
    }
  }

  return { estimatedTimeMinutes, filamentUsedMm, filamentUsedGrams, layerCount, nozzleTemp, bedTemp, printerIdentifier, filamentType, filamentBrand: null }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface ParserDefaults {
  density: number
  diameter: number
}

const DEFAULT_DENSITY = 1.24 // g/cm³ — PLA
const DEFAULT_DIAMETER = 1.75 // mm

/**
 * Parse a G-code file content string and return extracted metadata.
 *
 * @param content  Full G-code file text
 * @param defaults Optional density/diameter overrides (fallback: PLA 1.24 g/cm³ / 1.75mm)
 * @returns GcodeData if the slicer is recognised, null otherwise
 */
export function parseGcode(content: string, defaults?: ParserDefaults): GcodeData | null {
  if (!content || content.trim().length === 0) return null

  // Slicer detection only needs the first ~200 lines: the `generated by …`
  // comment is always near the top of every supported slicer.
  const allLines = content.split(/\r?\n/)
  const headLines = allLines.length > 200 ? allLines.slice(0, 200) : allLines

  const detected = detectSlicer(headLines)
  if (!detected) return null

  // For metadata extraction we walk ALL lines (header for Cura/S3D, footer
  // for PrusaSlicer/Orca/Bambu). Each extractor short-circuits once every
  // critical field is filled, so a 50k-line file still parses in milliseconds.
  const lines = allLines

  const density = defaults?.density ?? DEFAULT_DENSITY
  const diameter = defaults?.diameter ?? DEFAULT_DIAMETER

  let partial: Partial<GcodeData>

  switch (detected.slicerType) {
    case 'cura':
      partial = extractCura(lines, diameter, density)
      break
    case 'prusaslicer':
      partial = extractPrusa(lines, diameter, density)
      break
    case 'orcaslicer':
      partial = extractOrca(lines, diameter, density)
      break
    case 'bambustudio':
      partial = extractBambu(lines, diameter, density)
      break
    case 'simplify3d':
      partial = extractSimplify3D(lines, diameter, density)
      break
    default:
      return null
  }

  return {
    slicerName: detected.slicerName,
    slicerType: detected.slicerType,
    estimatedTimeMinutes: partial.estimatedTimeMinutes ?? null,
    filamentUsedMm: partial.filamentUsedMm ?? null,
    filamentUsedGrams: partial.filamentUsedGrams ?? null,
    layerCount: partial.layerCount ?? null,
    nozzleTemp: partial.nozzleTemp ?? null,
    bedTemp: partial.bedTemp ?? null,
    printerIdentifier: partial.printerIdentifier ?? null,
    filamentType: partial.filamentType ?? null,
    filamentBrand: partial.filamentBrand ?? null,
  }
}
