; generated by BambuStudio 01.09.05.51
;
; HEADER_BLOCK_START
; header_version = 1.0.0
; machine_name = Bambu Lab P1S 0.4 nozzle
; printer_model = C12
; nozzle_diameter = 0.4
; nozzle_type = hardened_steel
; HEADER_BLOCK_END
;
; CONFIG_BLOCK_START
; filament_type = PLA
; filament_vendor = Bambu Lab
; filament_ids = GFL00
; total filament used [g] = 18.50
; total filament used [mm] = 7480.20
; total estimated time (s) = 5580
; CONFIG_BLOCK_END
;
M190 S35 ; set bed temp
M109 S220 ; set nozzle temp
M1003 ; prime the nozzle
G28 ; home all axes
G1 Z2 F3000
G1 X5 Y5 F9000
G1 Z0.3 F3000
G1 X250 Y5 E40 F3000
