; generated by OrcaSlicer 2.1.1 on 2024-03-15 at 10:23:41 UTC
;
; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
;
; estimated printing time (normal mode) = 1h 30m 25s
;
; filament used [mm] = 3200.50
; filament used [cm3] = 7.70
; filament used [g] = 9.55
; filament cost = 0.12
;
; printer_model = Ender-3 V3 SE
; printer_settings_id = Creality Ender-3 V3 SE
; filament_type = PETG
; filament_vendor = eSUN
; nozzle_diameter = 0.40
; bed_temperature = 80
; first_layer_temperature = 240
;
M190 S80 ; bed temp
M104 S240
M109 S240
G28
G1 Z0.3 F3000
G1 X5 Y5 F3000
G1 X5 Y200 E20 F1500
