; generated by PrusaSlicer 2.7.2 on 2024-03-15 at 10:23:41 UTC
;
; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; support material extrusion width = 0.35mm
;
; estimated printing time (normal mode) = 2h 34m 0s
;
; filament used [mm] = 4521.23
; filament used [cm3] = 10.88
; filament used [g] = 13.49
; filament cost = 0.18
;
; printer_model = MK4
; printer_settings_id = Original Prusa MK4
; filament_type = PLA
; filament_vendor = Prusament
; nozzle_diameter = 0.40
; bed_temperature = 60
; first_layer_temperature = 215
;
M190 S60 ; set bed temperature
M104 S215 ; set temperature
M109 S215 ; wait for temperature
G28 ; Home axes
G1 Z0.3 F3000
G1 X2 Y3 F3000
G1 X2 Y200 E30 F1500
G1 X3 Y200 F5000
G1 X3 Y3 E60 F1500
