; GCode generated by Simplify3D(R) Version 5.1.2
;   Build time: 2 hours 15 minutes
;   Filament used: 4215.35mm (10.15cm3)
;   Notes:
;   Sliced by Simplify3D 5.1.2
;   machineType,ender3
;   printMaterial,PLA
;   printTemperature,205
;   printBedTemperature,60
;   numShells,3
;   layerHeight,0.2
;   platformTemp,60
;   extruderTemp,205
M109 S205
M190 S60
G28
G1 X0 Y0 Z5 F3000
G1 Z0.3 F1500
G1 X200 Y0 E40 F2000
